# Generated by Django 5.1 on 2024-12-29 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0003_servicio_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='departamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='condominio.departamento'),
            preserve_default=False,
        ),
    ]
