# Generated by Django 5.1 on 2024-12-29 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0006_pago_metodo_pago_pago_monto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='residente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condominio.residente'),
        ),
    ]
