# Generated by Django 5.1 on 2024-12-29 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0008_pago_facturas_alter_factura_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mantenimiento',
            name='pago',
        ),
    ]
