# Generated by Django 5.1 on 2024-12-29 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0009_remove_mantenimiento_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='residente',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='residente',
        ),
        migrations.RemoveField(
            model_name='residente',
            name='usuario',
        ),
        migrations.AddField(
            model_name='factura',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pago',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='residente',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='residente', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
