# Generated by Django 5.1 on 2024-12-29 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0010_remove_factura_residente_remove_pago_residente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residente',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condominio.departamento'),
        ),
    ]
