# Generated by Django 5.1 on 2024-12-29 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0011_alter_residente_departamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departamento',
            old_name='usuario',
            new_name='user',
        ),
    ]
