# Generated by Django 5.1 on 2024-12-31 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0014_alter_departamento_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='mantenimiento',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='monto_total',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='pago',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='servicio',
        ),
        migrations.AddField(
            model_name='pago',
            name='saldo_pendiente',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='factura',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condominio.departamento'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='descripcion',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado')], default='Pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='factura',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
