# Generated by Django 5.1 on 2024-12-31 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0015_remove_factura_mantenimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado')], max_length=50),
        ),
    ]
