# Generated by Django 5.1 on 2024-12-31 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0016_alter_factura_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='monto',
            new_name='monto_total',
        ),
    ]
