# Generated by Django 5.1 on 2024-12-31 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0017_rename_monto_factura_monto_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='servicios',
            field=models.ManyToManyField(to='condominio.servicio'),
        ),
    ]
