# Generated by Django 5.1 on 2024-12-31 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0018_alter_pago_servicios'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='mantenimientos',
            field=models.ManyToManyField(to='condominio.mantenimiento'),
        ),
    ]
