# Generated by Django 5.1 on 2024-12-31 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0019_pago_mantenimientos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='facturas',
        ),
        migrations.AddField(
            model_name='factura',
            name='pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='condominio.pago'),
        ),
    ]
