# Generated by Django 5.1.4 on 2025-01-04 20:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0020_remove_pago_facturas_factura_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
