# Generated by Django 5.1.4 on 2025-01-04 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0021_factura_monto_pagado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
