# Generated by Django 5.1 on 2025-01-05 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0022_alter_pago_fecha_vencimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='fecha_vencimiento',
        ),
    ]
