# Generated by Django 5.1 on 2025-01-12 22:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0024_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='saldo_pendiente',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
