# Generated by Django 5.1.4 on 2025-01-14 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0027_remove_notificacion_mensaje_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificacion',
            old_name='fecha_creacion',
            new_name='fecha',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='leido',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='usuario',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='mensaje',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificacion',
            name='titulo',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
