"""
Django settings for gestion_condominio project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from pathlib import Path
from django.forms.renderers import TemplatesSetting
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6g)n$$a9u9^@y)n3qb&sh09@x!y77#3vi^@jfhro9qy^bl2-%b'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# DEBUG = False

ALLOWED_HOSTS = ["Condominio.com"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',  # Sin espacio al final
    'condominio',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'condominio.middleware.DisableCacheMiddleware',
    'condominio.middleware.NoCacheMiddleware'
    
]

ROOT_URLCONF = 'gestion_condominio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gestion_condominio.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'Condominio.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATIC_URL = '/static/'

# Ruta donde se almacenan los archivos estáticos recopilados
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Directorios adicionales para buscar archivos estáticos
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
# Para el desarrollo, si estás trabajando localmente, es posible que también necesites añadir
STATICFILES_DIRS = [
     os.path.join(BASE_DIR, 'static'),  # O especifica la ruta absoluta de tu carpeta "static" si no está en el directorio base
]


# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 3600  # Expira en 1 hora (3600 segundos)
SESSION_COOKIE_HTTPONLY = True

SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True

# Para reforzar no-caché
CACHE_CONTROL_NO_STORE = True


# Configuración del correo electrónico
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # Usar el backend SMTP para enviar correos
EMAIL_HOST = 'smtp.gmail.com'  # Servidor de correo de Gmail
EMAIL_PORT = 587  # Puerto de Gmail
EMAIL_USE_TLS = True  # Usar TLS (recomendado)
EMAIL_HOST_USER = 'ricarberri@gmail.com'  # Tu correo de Gmail
EMAIL_HOST_PASSWORD = 'Tlkmi89#._'  # La contraseña de tu correo de Gmail (o usa una contraseña de aplicación)
DEFAULT_FROM_EMAIL = 'ricarberri@gmail.com'  # Correo desde el cual se enviarán los mensajes

# Para pruebas locales, si no quieres enviar correos reales
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # Muestra los correos en la consola

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')


log_dir = os.path.join(BASE_DIR, 'logs')
if not os.path.exists(log_dir):
    os.makedirs(log_dir)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        # Manejar logs y guardarlos en un archivo
        'file': {
            'level': 'INFO',  # El nivel mínimo de los logs que deseas capturar
            'class': 'logging.FileHandler',
            'filename': 'logs/django.log',  # Ruta donde se guardarán los logs
        },
        # Manejar los logs para que se muestren también en la consola
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        # Log para Django en general
        'django': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',  # Cambiar según el nivel que necesites (DEBUG, INFO, ERROR)
            'propagate': True,
        },
        # Log para tu aplicación en particular
        'condominio': {  # Reemplaza 'myapp' con el nombre de tu aplicación
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}